/* ZIP export module */

import { dataUriToBlob, extensionForAsset, slugify } from './utils.js';

const addTextFile = (zip, path, content) => zip.file(path, content);

const buildManifest = (assets) => JSON.stringify({
  generatedAt: new Date().toISOString(),
  product: 'HEX Asset Extractor Pro',
  assetCount: assets.length,
  assets: assets.map(asset => ({
    id: asset.id,
    name: asset.name,
    category: asset.category,
    mime: asset.mime,
    source: asset.source,
    size: asset.size,
    duplicate: asset.duplicate,
    url: asset.url || null
  }))
}, null, 2);

const downloadBlob = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
};

export const exportAssetsZip = async (assets, options = {}) => {
  if (!window.JSZip) throw new Error('JSZip failed to load. Please check your network connection.');
  const zip = new window.JSZip();
  const selectedAssets = options.imagesOnly ? assets.filter(asset => asset.category === 'image') : assets;

  if (!selectedAssets.length) throw new Error('No matching assets are available for export.');

  const embeddedFolder = zip.folder('embedded-assets');
  const externalFolder = zip.folder('external-assets');

  selectedAssets.forEach((asset, index) => {
    const extension = extensionForAsset(asset);
    const safeName = `${String(index + 1).padStart(3, '0')}-${slugify(asset.name || asset.category)}.${extension}`;
    if (asset.source === 'embedded' && asset.dataUri) {
      embeddedFolder.file(safeName, dataUriToBlob(asset.dataUri));
    } else if (asset.url) {
      addTextFile(externalFolder, safeName.replace(/\.[^.]+$/, '.url.txt'), asset.url);
    }
  });

  addTextFile(zip, 'manifest.json', buildManifest(selectedAssets));
  addTextFile(zip, 'README.txt', 'Generated by HEX Asset Extractor Pro. Embedded Base64 assets are exported as files. External assets are listed as URL references for secure client-side operation.');

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
  const fileName = options.imagesOnly ? 'hex-extracted-images.zip' : 'hex-all-assets.zip';
  downloadBlob(blob, fileName);
};
